name: 04 - Using Actions
on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v6

        - name: Printing Folders
          run: ls -la
        
        - name: Setup Node
          uses: actions/setup-node@v6
          with:
            # Version Spec of the version to use in SemVer notation.
            # It also admits such aliases as lts/*, latest, nightly and canary builds
            # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
            node-version: '24.x'
        - name: Install Dependencies
            #cd 04-using-actions/reate-app
          run: npm ci
          working-directory: 04-using-actions/reate-app
        - name: Linting
          run: npm run lint
          working-directory: 04-using-actions/reate-app