name: 11 - Working with Inputs

on: 
  pull_request:
  workflow_dispatch:
    inputs:
        dry-run: 
            type: boolean
            description: Skip deployment and only print build output
            default: false
        target: 
            type: environment
            required: true
            description: Which environment the workflow will target
        tag: 
            type: choice
            options:
             - v1
             - v2
             - v3
            description: Release from which to build and deploy
            default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Build
         #inputs.tag.options is invalid. inputs.tag is just the selected value like v1/v2/v3; 
         #there is no .options property at runtime.
          run: |
            echo "Building from tag using inputs.tag.options: ${{ inputs.tag.options }}"
            echo "Building from tag using inputs.tag: ${{ inputs.tag }}"
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.target }}
    if: ${{ !inputs.dry-run }}
    steps:
        - name: Deploy
          run: echo Deploying to ${{ inputs.target }}