name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}
on: 
  workflow_dispatch:
    inputs:
        target-env:
            type: choice
            options:
             - dev
             - prod
            description: Environment
            default: dev
env:
    working-directory: 17-custom-actions/react-app
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ${{ env.working-directory }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Setup Node and NPM Dependencies
          uses: ./.github/actions/composite-cache-deps
          id: setup-deps
          with:
            node-version: 24.x
            working-dir: ${{ env.working-directory }}
            target-env: ${{ inputs.target-env }}

        - name: Print setup deps output
          run: |
           echo Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}
           echo random-output: ${{ steps.setup-deps.outputs.random-output }}

        - name: Testing
          run: npm run test

        - name: Building
          run: npm run build

        - name: Deploying to ${{ inputs.target-env }}
          run: echo Deploying to ${{ inputs.target-env }}.